In [ ]:
import os
import glob
from torch.utils.data import Dataset
from PIL import Image
import torchvision.transforms as T
import torch
import numpy as np
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, random_split
from PIL import Image
import torchvision.transforms as T
import torch
import numpy as np

In [6]:

IMG_PATH = r"C:\Users\harry\Documents\Harry\UQ\sem2_2025\DATA7903\DATA7901\gwfss\images"
MASK_PATH = r"C:\Users\harry\Documents\Harry\UQ\sem2_2025\DATA7903\DATA7901\gwfss\masks_grayscale"


In [ ]:


class WheatSegmentationDataset(Dataset):
    def __init__(self, image_root, mask_root, transform=None):
        self.image_root = image_root
        self.mask_root = mask_root
        self.transform = transform  # for images only
        # ... build self.image_paths, self.mask_paths as you already do ...

        # Recursively find all image files under image_root
        self.image_paths = sorted(glob.glob(os.path.join(image_root, '**', '*.png'), recursive=True))

        # Derive corresponding mask paths by replacing the image root with mask root
        self.mask_paths = [
            os.path.join(mask_root, os.path.relpath(p, image_root)) for p in self.image_paths
        ]


        self.resize_img = T.Resize((512, 512))                                 # bilinear
        self.resize_mask = T.Resize((512, 512), interpolation=Image.NEAREST)   # keep labels

    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert("RGB")
        mask  = Image.open(self.mask_paths[idx]).convert("L")

        image = self.resize_img(image)
        mask  = self.resize_mask(mask)

        if self.transform:
            image = self.transform(image)
        else:
            image = T.ToTensor()(image)
            image = T.Normalize([0.5]*3, [0.5]*3)(image)



        mask = torch.as_tensor(np.array(mask), dtype=torch.long)  # [H,W]
        return image, mask

    def __len__(self):
        return len(self.image_paths)


## Calculating the Dataset mean and std

In [7]:

transform = T.Compose([
    T.Resize((512, 512)),
    T.ToTensor(),
    #T.Normalize([0.5]*3, [0.5]*3),
])

dataset = WheatSegmentationDataset(IMG_PATH, MASK_PATH, transform=transform)


loader = DataLoader(dataset, batch_size=16, shuffle=False)

# Accumulate pixel values
mean = 0.0
std = 0.0
nb_samples = 0

for images, _ in loader:
    # images shape: [B, C, H, W]
    batch_samples = images.size(0)
    images = images.view(batch_samples, images.size(1), -1)  # [B, C, H*W]
    
    mean += images.mean(2).sum(0)   # mean over pixels, sum over batch
    std += images.std(2).sum(0)     # std over pixels, sum over batch
    nb_samples += batch_samples

mean /= nb_samples
std /= nb_samples

print(f"Dataset Mean: {mean}")
print(f"Dataset Std:  {std}")

Dataset Mean: tensor([0.3481, 0.3549, 0.2532])
Dataset Std:  tensor([0.1830, 0.1921, 0.1563])


In [8]:
transform = T.Compose([
    T.Resize((512, 512)),
    T.ToTensor(),
    T.Normalize(mean.tolist(), std.tolist())
])

dataset = WheatSegmentationDataset(IMG_PATH, MASK_PATH, transform=transform)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8)

In [9]:
import torchvision.models.segmentation as models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.deeplabv3_resnet50(pretrained=False, num_classes=4)
model.to(device)

c:\Users\harry\.conda\envs\data7903-proj\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\harry\.conda\envs\data7903-proj\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


DeepLabV3(
  (backbone): IntermediateLayerGetter(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (downsample): Se

In [10]:
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-4)

def train_one_epoch(model, loader):
    model.train()
    total_loss = 0

    for images, masks in loader:
        images, masks = images.to(device), masks.to(device)

        optimizer.zero_grad()
        outputs = model(images)['out']
        outputs = F.interpolate(outputs, size=(512, 512), mode='bilinear', align_corners=False)

        loss = criterion(outputs, masks)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    # ✅ Must return the average loss
    return total_loss / len(loader)

In [13]:
def compute_iou(pred, target, num_classes):
    """
    pred: [N, H, W] predicted class indices
    target: [N, H, W] ground truth
    """
    ious = []
    for cls in range(num_classes):
        pred_inds = (pred == cls)
        target_inds = (target == cls)
        intersection = (pred_inds & target_inds).sum().item()
        union = (pred_inds | target_inds).sum().item()
        if union == 0:
            ious.append(float('nan'))  # skip empty class
        else:
            ious.append(intersection / union)
    return ious  # list of IoUs per class

In [14]:
def evaluate(model, dataloader, num_classes=4):
    model.eval()
    total_correct = 0
    total_pixels = 0
    iou_list = []

    with torch.no_grad():
        for images, masks in dataloader:
            images, masks = images.to(device), masks.to(device)

            outputs = model(images)["out"]
            preds = torch.argmax(outputs, dim=1)  # [B,H,W]

            total_correct += (preds == masks).sum().item()
            total_pixels += torch.numel(masks)

            iou = compute_iou(preds, masks, num_classes)
            iou_list.append(iou)

    pixel_acc = 100.0 * total_correct / total_pixels
    mean_iou = torch.tensor(iou_list).nanmean(0).mean().item() * 100

    return pixel_acc, mean_iou

In [15]:
epochs = 25
train_losses = []
val_accuracies = []
val_mious = []

for epoch in range(epochs):
    train_loss = train_one_epoch(model, train_loader)
    val_acc, val_miou = evaluate(model, val_loader, num_classes=4)

    train_losses.append(train_loss)
    val_accuracies.append(val_acc)
    val_mious.append(val_miou)

    print(f"Epoch {epoch+1}: Train Loss = {train_loss:.4f}, "
          f"Val Pixel Acc = {val_acc:.2f}%, Val mIoU = {val_miou:.2f}%")

# Save metrics
df_metrics = pd.DataFrame({
    'Epoch': list(range(1, epochs + 1)),
    'Train_Loss': train_losses,
    'Val_Acc': val_accuracies,
    'Val_mIoU': val_mious
})

df_metrics.to_csv('training_metrics.csv', index=False)

Epoch 1: Train Loss = 0.6749, Val Pixel Acc = 80.92%, Val mIoU = 51.99%
Epoch 2: Train Loss = 0.5099, Val Pixel Acc = 83.44%, Val mIoU = 55.09%
Epoch 3: Train Loss = 0.4441, Val Pixel Acc = 84.92%, Val mIoU = 59.40%
Epoch 4: Train Loss = 0.4080, Val Pixel Acc = 84.38%, Val mIoU = 61.08%
Epoch 5: Train Loss = 0.3696, Val Pixel Acc = 84.94%, Val mIoU = 61.12%
Epoch 6: Train Loss = 0.3569, Val Pixel Acc = 86.14%, Val mIoU = 62.10%
Epoch 7: Train Loss = 0.3324, Val Pixel Acc = 86.36%, Val mIoU = 63.76%
Epoch 8: Train Loss = 0.3026, Val Pixel Acc = 86.54%, Val mIoU = 63.80%
Epoch 9: Train Loss = 0.2889, Val Pixel Acc = 86.73%, Val mIoU = 63.59%
Epoch 10: Train Loss = 0.2849, Val Pixel Acc = 64.78%, Val mIoU = 47.97%
Epoch 11: Train Loss = 0.2840, Val Pixel Acc = 86.73%, Val mIoU = 65.26%
Epoch 12: Train Loss = 0.2598, Val Pixel Acc = 86.75%, Val mIoU = 65.66%
Epoch 13: Train Loss = 0.2409, Val Pixel Acc = 87.22%, Val mIoU = 65.17%
Epoch 14: Train Loss = 0.2313, Val Pixel Acc = 87.27%, Val m

In [11]:
import os
from PIL import Image
import glob

image_root = r"C:\Users\harry\Documents\Harry\UQ\sem2_2025\DATA7903\DATA7901\gwfss\images"
image_paths = glob.glob(os.path.join(image_root, '**', '*.png'), recursive=True)

sizes = {}

for path in image_paths:
    with Image.open(path) as img:
        size = img.size  # (width, height)
        sizes[size] = sizes.get(size, 0) + 1

for size, count in sizes.items():
    print(f"Size {size}: {count} images")

Size (512, 512): 987 images
Size (1024, 1024): 109 images


In [16]:
from sklearn.metrics import confusion_matrix
import numpy as np
import torch.nn.functional as F

all_preds, all_labels = [], []

model.eval()
with torch.no_grad():
    for images, masks in val_loader:
        images = images.to(device)
        masks  = masks.to(device).long()

        logits = model(images)['out']  # one forward
        logits = F.interpolate(logits, size=masks.shape[-2:], mode='bilinear', align_corners=False)
        preds  = logits.argmax(dim=1)

        # (Optional) sanity check shapes
        # print("preds:", preds.shape, "masks:", masks.shape)

        all_preds.append(preds.cpu().numpy().ravel())
        all_labels.append(masks.cpu().numpy().ravel())

y_pred = np.concatenate(all_preds)
y_true = np.concatenate(all_labels)

cm = confusion_matrix(y_true, y_pred, labels=[0,1,2,3])  # background, head, stem, leaf (adjust order if needed)
print(cm)

[[15545763   121274    45870  2946423]
 [   94720  4553186    15566   460384]
 [   64524    49629   630333  1072990]
 [ 1764092   368481   315767 29622678]]
